// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Account")]
[Index("Email", Name = "UQ__Account__A9D105344CD8D0DA", IsUnique = true)]
public partial class Account
{
    [Key]
    public Guid Id { get; set; }

    public Guid RoleId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string HashPassword { get; set; }

    public int? Level { get; set; }

    [Required]
    [Unicode(false)]
    public string VerifyToken { get; set; }

    [Required]
    [StringLength(100)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateAt { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Allergy> Allergies { get; set; } = new List<Allergy>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    [InverseProperty("Account")]
    public virtual ICollection<DeviceToken> DeviceTokens { get; set; } = new List<DeviceToken>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Dish> Dishes { get; set; } = new List<Dish>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    [InverseProperty("Account")]
    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();

    [InverseProperty("Account")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    [InverseProperty("Account")]
    public virtual Profile Profile { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<RetreatGroupMember> RetreatGroupMembers { get; set; } = new List<RetreatGroupMember>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<RetreatGroupMessage> RetreatGroupMessages { get; set; } = new List<RetreatGroupMessage>();

    [InverseProperty("Monk")]
    public virtual ICollection<RetreatGroup> RetreatGroups { get; set; } = new List<RetreatGroup>();

    [InverseProperty("Monk")]
    public virtual ICollection<RetreatMonk> RetreatMonks { get; set; } = new List<RetreatMonk>();

    [InverseProperty("Participant")]
    public virtual ICollection<RetreatRegistrationParticipant> RetreatRegistrationParticipants { get; set; } = new List<RetreatRegistrationParticipant>();

    [InverseProperty("CreateByNavigation")]
    public virtual ICollection<RetreatRegistration> RetreatRegistrations { get; set; } = new List<RetreatRegistration>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Retreat> Retreats { get; set; } = new List<Retreat>();

    [ForeignKey("RoleId")]
    [InverseProperty("Accounts")]
    public virtual Role Role { get; set; }

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<ToolHistory> ToolHistories { get; set; } = new List<ToolHistory>();
}