// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Allergy")]
public partial class Allergy
{
    [Key]
    public Guid Id { get; set; }

    public Guid IngredientId { get; set; }

    public Guid AccountId { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Allergies")]
    public virtual Account Account { get; set; }

    [ForeignKey("IngredientId")]
    [InverseProperty("Allergies")]
    public virtual Ingredient Ingredient { get; set; }
}