// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("DishIngredient")]
public partial class DishIngredient
{
    [Key]
    public Guid Id { get; set; }

    public Guid DishId { get; set; }

    public Guid IngredientId { get; set; }

    [ForeignKey("DishId")]
    [InverseProperty("DishIngredients")]
    public virtual Dish Dish { get; set; }

    [ForeignKey("IngredientId")]
    [InverseProperty("DishIngredients")]
    public virtual Ingredient Ingredient { get; set; }
}