// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Dish")]
public partial class Dish
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid DishTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool IsHalal { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateAt { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("Dishes")]
    public virtual Account CreatedByNavigation { get; set; }

    [InverseProperty("Dish")]
    public virtual ICollection<DishIngredient> DishIngredients { get; set; } = new List<DishIngredient>();

    [ForeignKey("DishTypeId")]
    [InverseProperty("Dishes")]
    public virtual DishType DishType { get; set; }

    [InverseProperty("Dish")]
    public virtual ICollection<MenuDish> MenuDishes { get; set; } = new List<MenuDish>();
}