// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Menu")]
public partial class Menu
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    [Column(TypeName = "date")]
    public DateTime CookDate { get; set; }

    public bool IsBreakfast { get; set; }

    public bool IsLunch { get; set; }

    public bool IsDinner { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("Menus")]
    public virtual Account CreatedByNavigation { get; set; }

    [InverseProperty("Menu")]
    public virtual ICollection<MenuDish> MenuDishes { get; set; } = new List<MenuDish>();
}