// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("MenuDish")]
public partial class MenuDish
{
    [Key]
    public Guid Id { get; set; }

    public Guid MenuId { get; set; }

    public Guid DishId { get; set; }

    [ForeignKey("DishId")]
    [InverseProperty("MenuDishes")]
    public virtual Dish Dish { get; set; }

    [ForeignKey("MenuId")]
    [InverseProperty("MenuDishes")]
    public virtual Menu Menu { get; set; }
}