// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Notification")]
public partial class Notification
{
    [Key]
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    [Required]
    public string Content { get; set; }

    [StringLength(255)]
    public string Url { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    public bool IsRead { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Notifications")]
    public virtual Account Account { get; set; }
}