// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public Guid Id { get; set; }

    public Guid RetreatRegId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    public Guid PaypalOrderId { get; set; }

    [Required]
    [StringLength(255)]
    public string Status { get; set; }

    [ForeignKey("RetreatRegId")]
    [InverseProperty("Payments")]
    public virtual RetreatRegistration RetreatReg { get; set; }
}