// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Post")]
public partial class Post
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateAt { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("Posts")]
    public virtual Account CreatedByNavigation { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();
}