// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Profile")]
[Index("AccountId", Name = "UQ__Profile__349DA5A712802AA3", IsUnique = true)]
[Index("PhoneNumber", Name = "UQ__Profile__85FB4E38853C84A6", IsUnique = true)]
public partial class Profile
{
    [Key]
    public Guid AccountId { get; set; }

    [Required]
    [StringLength(255)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(255)]
    public string LastName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateOfBirth { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string Gender { get; set; }

    [Unicode(false)]
    public string Avatar { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Profile")]
    public virtual Account Account { get; set; }
}