// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("RetreatGroupMember")]
public partial class RetreatGroupMember
{
    [Key]
    public Guid Id { get; set; }

    public Guid GroupId { get; set; }

    public Guid MemberId { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("RetreatGroupMembers")]
    public virtual RetreatGroup Group { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("RetreatGroupMembers")]
    public virtual Account Member { get; set; }
}