// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("RetreatMonk")]
public partial class RetreatMonk
{
    [Key]
    public Guid Id { get; set; }

    public Guid MonkId { get; set; }

    public Guid RetreatId { get; set; }

    [ForeignKey("MonkId")]
    [InverseProperty("RetreatMonks")]
    public virtual Account Monk { get; set; }

    [ForeignKey("RetreatId")]
    [InverseProperty("RetreatMonks")]
    public virtual Retreat Retreat { get; set; }
}