// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

public partial class RetreatRegistrationParticipant
{
    [Key]
    public Guid Id { get; set; }

    public Guid ParticipantId { get; set; }

    public Guid RetreatRegId { get; set; }

    [ForeignKey("ParticipantId")]
    [InverseProperty("RetreatRegistrationParticipants")]
    public virtual Account Participant { get; set; }

    [ForeignKey("RetreatRegId")]
    [InverseProperty("RetreatRegistrationParticipants")]
    public virtual RetreatRegistration RetreatReg { get; set; }
}