// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("RetreatGroupMessage")]
public partial class RetreatGroupMessage
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid GroupId { get; set; }

    public Guid? ReplyTo { get; set; }

    [Required]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateAt { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("RetreatGroupMessages")]
    public virtual Account CreatedByNavigation { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("RetreatGroupMessages")]
    public virtual RetreatGroup Group { get; set; }
}