// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("RetreatSchedule")]
public partial class RetreatSchedule
{
    [Key]
    public Guid Id { get; set; }

    public Guid RetreatId { get; set; }

    public Guid GroupId { get; set; }

    public Guid? RetreatLessonId { get; set; }

    public Guid? UsedRoomId { get; set; }

    [Column(TypeName = "date")]
    public DateTime LessonDate { get; set; }

    public TimeSpan LessonStart { get; set; }

    public TimeSpan LessonEnd { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("RetreatSchedules")]
    public virtual RetreatGroup Group { get; set; }

    [ForeignKey("RetreatId")]
    [InverseProperty("RetreatSchedules")]
    public virtual Retreat Retreat { get; set; }

    [ForeignKey("RetreatLessonId")]
    [InverseProperty("RetreatSchedules")]
    public virtual RetreatLesson RetreatLesson { get; set; }

    [ForeignKey("UsedRoomId")]
    [InverseProperty("RetreatSchedules")]
    public virtual Room UsedRoom { get; set; }
}