// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Retreat")]
public partial class Retreat
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(16, 2)")]
    public decimal Cost { get; set; }

    public int Capacity { get; set; }

    public int Duration { get; set; }

    [Column(TypeName = "date")]
    public DateOnly StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateOnly EndDate { get; set; }

    [Required]
    [StringLength(100)]
    public string Status { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("Retreats")]
    public virtual Account CreatedByNavigation { get; set; }

    [InverseProperty("Retreat")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("Retreat")]
    public virtual ICollection<RetreatGroup> RetreatGroups { get; set; } = new List<RetreatGroup>();

    [InverseProperty("Retreat")]
    public virtual ICollection<RetreatLesson> RetreatLessons { get; set; } = new List<RetreatLesson>();

    [InverseProperty("Retreat")]
    public virtual ICollection<RetreatMonk> RetreatMonks { get; set; } = new List<RetreatMonk>();

    [InverseProperty("Retreat")]
    public virtual ICollection<RetreatRegistration> RetreatRegistrations { get; set; } = new List<RetreatRegistration>();

    [InverseProperty("Retreat")]
    public virtual ICollection<RetreatSchedule> RetreatSchedules { get; set; } = new List<RetreatSchedule>();

    [InverseProperty("Retreat")]
    public virtual ICollection<ToolHistory> ToolHistories { get; set; } = new List<ToolHistory>();
}