// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("Room")]
public partial class Room
{
    [Key]
    public Guid Id { get; set; }

    public Guid RoomTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int Capacity { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("UsedRoom")]
    public virtual ICollection<RetreatSchedule> RetreatSchedules { get; set; } = new List<RetreatSchedule>();

    [ForeignKey("RoomTypeId")]
    [InverseProperty("Rooms")]
    public virtual RoomType RoomType { get; set; }
}