// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCSM_Data.Entities;

[Table("ToolHistory")]
public partial class ToolHistory
{
    [Key]
    public Guid Id { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid RetreatId { get; set; }

    public Guid ToolId { get; set; }

    public Guid ToolOpId { get; set; }

    public int NumOfTool { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("ToolHistories")]
    public virtual Account CreatedByNavigation { get; set; }

    [ForeignKey("RetreatId")]
    [InverseProperty("ToolHistories")]
    public virtual Retreat Retreat { get; set; }

    [ForeignKey("ToolId")]
    [InverseProperty("ToolHistories")]
    public virtual Tool Tool { get; set; }

    [ForeignKey("ToolOpId")]
    [InverseProperty("ToolHistories")]
    public virtual ToolOperation ToolOp { get; set; }
}